-- The deal ledger: consented, transacted-rate datapoints (the moat asset) plus
-- funnel telemetry for the Seed-raising metric (GMV routed + % logging a real deal).

create table if not exists public.deals (
  id text primary key,
  creator_id uuid not null references public.creators (id) on delete cascade,
  brand_name text not null,
  deliverables jsonb not null,
  amount numeric(12, 2) not null check (amount > 0),
  currency text not null check (currency in ('INR', 'AED')),
  status text not null default 'offered'
    check (status in ('offered', 'accepted', 'delivered', 'paid')),
  offered_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists deals_creator_idx on public.deals (creator_id);

alter table public.deals enable row level security;

drop policy if exists deals_select_own on public.deals;
create policy deals_select_own on public.deals
  for select to authenticated using (auth.uid() = creator_id);

drop policy if exists deals_insert_own on public.deals;
create policy deals_insert_own on public.deals
  for insert to authenticated with check (auth.uid() = creator_id);

drop policy if exists deals_update_own on public.deals;
create policy deals_update_own on public.deals
  for update to authenticated
  using (auth.uid() = creator_id)
  with check (auth.uid() = creator_id);

create table if not exists public.funnel_events (
  id bigint generated by default as identity primary key,
  creator_id uuid references public.creators (id) on delete set null,
  type text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists funnel_events_creator_idx on public.funnel_events (creator_id);
create index if not exists funnel_events_type_idx on public.funnel_events (type);

-- Events are written server-side (service role bypasses RLS) and are not readable
-- by anon/authenticated: RLS enabled with no policy => default deny for those roles.
alter table public.funnel_events enable row level security;
